### ISSUE TITLE
Many Errors for compiling the Streaming version

### ISSUE THREAD

**Issue by TommyGx** [G6EJD/ESP32-42e-Paper-Weather-Display-#3]
Hey,

as i said i get the following Errorcodes, I'm using the latest Json library and the one you linked in the code, but nothing seems really to help somehow.

```
C:\Users\Tommy\Downloads\ESP32-42e-Paper-Weather-Display--master\ESP32_OWM_Current_Forecast_Streaming_75on42_epaper_v1\ESP32_OWM_Current_Forecast_Streaming_75on42_epaper_v1.ino:` In function 'bool DecodeWeather(Stream&, String)':

ESP32_OWM_Current_Forecast_Streaming_75on42_epaper_v1:544:3: error: 'DynamicJsonDocument' was not declared in this scope

   DynamicJsonDocument doc(50*1024);

   ^

ESP32_OWM_Current_Forecast_Streaming_75on42_epaper_v1:545:3: error: 'DeserializationError' was not declared in this scope

   DeserializationError error = deserializeJson(doc, json_stream);

   ^

ESP32_OWM_Current_Forecast_Streaming_75on42_epaper_v1:546:7: error: 'error' was not declared in this scope

   if (error) {

       ^

ESP32_OWM_Current_Forecast_Streaming_75on42_epaper_v1:552:22: error: 'doc' was not declared in this scope

   JsonObject& root = doc.as<JsonObject>();

                      ^

ESP32_OWM_Current_Forecast_Streaming_75on42_epaper_v1:552:39: error: expected primary-expression before '>' token

   JsonObject& root = doc.as<JsonObject>();

                                       ^

ESP32_OWM_Current_Forecast_Streaming_75on42_epaper_v1:552:41: error: expected primary-expression before ')' token

   JsonObject& root = doc.as<JsonObject>();

                                         ^

Mehrere Bibliotheken wurden für "ArduinoJson.h" gefunden
 Benutzt: C:\Users\Tommy\Documents\Arduino\libraries\ArduinoJson
 Nicht benutzt: C:\Users\Tommy\Documents\Arduino\libraries\arduino_350712
Mehrere Bibliotheken wurden für "WiFi.h" gefunden
 Benutzt: C:\Users\Tommy\Documents\Arduino\hardware\espressif\esp32\libraries\WiFi
 Nicht benutzt: C:\Program Files (x86)\Arduino\libraries\WiFi
Mehrere Bibliotheken wurden für "SPI.h" gefunden
 Benutzt: C:\Users\Tommy\Documents\Arduino\hardware\espressif\esp32\libraries\SPI
 Nicht benutzt: C:\Program Files (x86)\Arduino\libraries\SPI
exit status 1
'DynamicJsonDocument' was not declared in this scope

```

I'm not sure if i'm missing any other Library or if it's another problem with the Json, because i had a lot of issues with it, anyhow the other code worked.

Also, i saw you have a battery-charge-read feature. Do you want to tell me what Powersupply you are using that this works? :-)

Thanks and Kind regards, Tommy

**Comment by SimonRafferty** [comment]
Dear Tommy,

JSON errors are usually due to how the Arduino IDE is communicating with
the ESP32.  Some of the boards I tried just refused to play, even when I'd
installed the recommended driver.  I had most luck with the AdaFruit
Feather 32.  The code doesn't use JSON itself - so I'd look at the board /
driver.

It has a socket for a 3.6v LiPo battery - and you can read it's voltage
through, if I remember correctly, pin 12.  There is a battery monitor
function (can't remember it's name - but search for Battery.  It will point
you in the right direction.  If you use a voltage divider - you can use any
Analog pin.  The ESP runs on 3.3v and the battery can be up to 4.5v  If you
connect a 10k resistor from the battery positive to the Analog pin of your
choice, and a 22k resistor from that pin to Gnd - the pin will see 3.1v
when the battery is at 4.5.  The value will be between 0 and 1023 for 0 to
3.3v.  At 3.1V it will read 961.  If you divide the reading by 213.5 it
will give you the battery voltage in volts.  Remember to use floating point
variables!

Good luck.

*Simon Rafferty* - SFX Design Engineer
email - simon1@psi-design.co.uk <jhmarsh69@gmail.com>
Mobile - 07774 956461

*FFSO Ltd*
SFX Department:
Unit 18 Fairway Drive
Greenford
UB6 8PW

Production:


*J/K Block Shepperton Studios.Studios Road,Shepperton, TW17 0QD*

**Comment by G6EJD** [comment]
Extract from the Readme:

The 'streaming' version requires *** Arduino JSON v6 or above *** it streams the Openweather and processes the data as received, rather than downloading all the data first, then decoding it. It uses a lot less memory this way.

*** Use Arduino JSON v5.13.3 for the other versions.

Whether you can read battery voltage or not depends on the development board type, I use the Wemos D32 that uses GPIO35 to which is connected a 100K-100K voltage divider, but you can easily wire that up and use any pin by attaching an ADC to the pin and then reading the voltage.

The JSON library is not yet consolidated in a form that can be used easily so I'm keeping them separate at the moment until v6 and above is no-longer a beta version, when I will make the transition to the new format.

**Comment by G6EJD** [comment]
If your using the latest beta 6.5 etc, then change this line:
  JsonObject& root = doc.as<JsonObject>();
to:
  JsonObject root = doc.as<JsonObject>();

AND this line:
    JsonArray& list                  = root["list"];
to:
    JsonArray list                  = root["list"];

It is beta software (JSON) so we have to expect changes to be made.

**Comment by G6EJD** [comment]
I have now updated the code to reflect the changes needed in the latest JSON library, everything compiles and decodes and displays correctly. For this streaming version you can use the latest version of Arduino JSON 6.5.0

**Comment by TommyGx** [comment]
thank you man! i'll try it as soon as possible :-)
